# Limpiando puntos de interés

In [40]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
pd.set_option('display.max_rows', 500)

In [37]:
projectfolder = "/Users/upar/Library/CloudStorage/OneDrive-UniversidaddelosAndes/00 SCHOOL/0-Semesters Archive/2022-20/5-Taller_ARCGIS-GIS/2-Evaluaciones/Proyecto_final/data_analysis/"
osm = pd.read_csv(f"{projectfolder+'Data/osm_bogota2.csv'}")
osm2 = pd.read_csv(f"{projectfolder+'Data/osmbog.csv'}", on_bad_lines="warn", delimiter=";")

In [41]:
osm2.fclass.value_counts()

restaurant             3371
bakery                 1159
pharmacy               1137
convenience            1131
cafe                   1117
fast_food              1094
supermarket            1041
clothes                1011
hairdresser             939
doityourself            677
bank                    625
bar                     527
stationery              516
shoe_shop               458
travel_agent            408
butcher                 398
bench                   394
laundry                 377
waste_basket            355
beauty_shop             335
dentist                 324
greengrocer             307
furniture_shop          303
beverages               287
school                  268
atm                     267
post_office             227
optician                204
chemist                 203
bicycle_shop            201
hotel                   191
playground              187
mobile_phone_shop       169
veterinary              155
florist                 142
clinic                  130
artwork                  95
pub                      89
kindergarten             88
car_wash                 86
department_store         85
car_dealership           81
hostel                   76
bookshop                 74
computer_shop            71
tourist_info             71
camera_surveillance      70
toilet                   68
doctors                  64
community_centre         61
memorial                 60
jeweller                 58
market_place             57
gift_shop                53
hospital                 52
telephone                51
police                   51
nightclub                49
post_box                 48
general                  47
sports_shop              46
library                  42
embassy                  41
sports_centre            39
cinema                   38
college                  37
toy_shop                 37
dog_park                 36
viewpoint                35
recycling                35
shelter                  32
theatre                  31
university               31
comms_tower              30
museum                   28
attraction               28
recycling_glass          27
fountain                 27
town_hall                26
park                     25
bicycle_rental           21
guesthouse               20
outdoor_shop             20
kiosk                    20
mall                     19
fire_station             18
motel                    18
courthouse               16
food_court               16
pitch                    14
video_shop               13
monument                 11
tower                    11
drinking_water           10
arts_centre               9
biergarten                7
swimming_pool             7
picnic_site               6
vending_machine           6
ruins                     5
water_tower               5
water_well                4
car_rental                4
garden_centre             4
wayside_shrine            3
chalet                    2
camp_site                 2
vending_any               2
vending_parking           2
caravan_site              1
castle                    1
newsagent                 1
recycling_clothes         1
prison                    1
alpine_hut                1
hunting_stand             1
stadium                   1
zoo                       1
water_works               1
nursing_home              1
Name: fclass, dtype: int64

In [39]:
osm2

        OID_       osm_id  code          fclass                  name
0          3    255471144  2904        fountain
1          4    261139202  2541  car_dealership               Renault
2          5    261664692  2528     greengrocer
3          6    262567789  2301      restaurant  La Casa de la Abuela
4          7    264785624  2301      restaurant      Vegetariano Vega
...      ...          ...   ...             ...                   ...
23212  82488  10261567185  2303            cafe          Bitcoin café
23213  82490  10262581171  2515        bookshop   Ediciones El Grillo
23214  82491  10262588099  2301      restaurant               La Fama
23215  82492  10262602909  2301      restaurant            El Libanés
23216  82505  10265787495  2205      playground

[23217 rows x 5 columns]

In [16]:
osm[osm["Count"]>10]

(81, 2)

In [17]:
osm[osm["Count"]>10].sort_values(by="Count")

                  fclass  Count
64                  mall   12.0
43          fire_station   13.0
109           video_shop   13.0
34            courthouse   15.0
61                 kiosk   20.0
41               embassy   21.0
45            food_court   21.0
12        bicycle_rental   21.0
73          outdoor_shop   22.0
77                 pitch   24.0
30           comms_tower   24.0
46              fountain   25.0
5             attraction   26.0
104             toy_shop   28.0
52            guesthouse   29.0
85             recycling   31.0
69                museum   32.0
110            viewpoint   32.0
90               shelter   33.0
99               theatre   33.0
18   camera_surveillance   34.0
93           sports_shop   34.0
27                cinema   36.0
68                 motel   37.0
106           university   38.0
92         sports_centre   39.0
100               toilet   41.0
63               library   41.0
65              memorial   42.0
101         tourist_info   42.0
29               college   45.0
49             gift_shop   46.0
3                artwork   48.0
71             nightclub   50.0
98             telephone   53.0
37               doctors   56.0
74                  park   57.0
59              jeweller   58.0
31      community_centre   61.0
55                hostel   62.0
32         computer_shop   65.0
15              bookshop   68.0
60          kindergarten   70.0
83                   pub   74.0
22              car_wash   78.0
20        car_dealership   79.0
79                police   80.0
54              hospital   82.0
36      department_store   97.0
108           veterinary  124.0
44               florist  132.0
81           post_office  136.0
78            playground  142.0
10                 bench  145.0
66     mobile_phone_shop  152.0
56                 hotel  154.0
13          bicycle_shop  158.0
11             beverages  162.0
26               chemist  168.0
111         waste_basket  183.0
72              optician  190.0
47        furniture_shop  234.0
4                    atm  235.0
51           greengrocer  251.0
9            beauty_shop  282.0
35               dentist  307.0
62               laundry  339.0
16               butcher  351.0
89                school  384.0
91             shoe_shop  420.0
95            stationery  421.0
105         travel_agent  474.0
8                    bar  484.0
39          doityourself  542.0
7                   bank  591.0
53           hairdresser  812.0
28               clothes  837.0
42             fast_food  898.0
96           supermarket  904.0
17                  cafe  968.0
33           convenience  983.0

Habiendo escogido estos 81 puntos de interés de los cuáles hay por lo menos 10 datos en Bogotá (umbral escogido arbitrariamente) procedo a categorizarlos en por lo menos 5 categorías. A mano y bajo mi propio criterio categoricé estos establecimientos bajo las siguientes categorías:

CULTURAL
- artwork
- bookshop
- cinema
- community_centre
- fountain
- library
- memorial
- museum
- nightclub
- park
- playground
- pub
- sports_centre
- theatre
- viewpoint


OTHER
- atm
- bank
- bar
- bicycle_rental
- camera_surveillance
- car_dealership
- car_wash
- chemist
- comms_tower
- courthouse
- doctors
- doityourself
- embassy
- fire_station
- guesthouse
- hospital
- hostel
- hotel
- kindergarten
- kiosk
- motel
- optician
- police
- post_office
- pub
- recycling
- telephone
- waste_basket


EDUCACIÓN
- university
- college
- school


OCIO
- attraction
- sports_centre
- library
- park


ALIMENTACIÓN
- beauty_shop
- beverages
- butcher
- cafe
- fast_food
- food_court
- greengrocer


COMPRAS
- clothes
- computer_shop
- convenience
- dentist
- department_store
- florist
- furniture_shop
- gift_shop
- hairdresser
- jeweller
- laundry
- mall
- mobile_phone_shop
- outdoor_shop
- shelter
- shoe_shop
- sports_shop
- stationery
- supermarket
- toy_shop
- veterinary
- video_shop

Dada la importancia y el número de ciertas observaciones el análisis preliminar exploratorio lo haré únicamente con los siguientes ítems que son un subconjunto de las listas en las categorías de arriba:

CULTURAL:
- park
- museum
- artwork
- art_centre

EDUCACIÓN:

- school
- university
- college

ALIMENTACIÓN:
- supermarket
- convenience
- fast_food
- greengrocer
- restaurant

SERVICIOS:
- bank
- optician
- doctors
- beauty_shop
- atm

OCIO:

- bar
- mall
- theatre
- cinema

In [51]:
"beauty_shop" in osm2.fclass.value_counts()

True